trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self
    submodules: true
  - task: AzureStaticWebApp@0
    inputs:
      app_location: '/Website'
      azure_static_web_apps_api_token: 'e398e7d30418b79fde69268137357a0ed39222903863530793fd7b3c983c4d2e0-643000c3-e271-4f41-bdeb-b59abe196b1500353071'