trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self
    submodules: true
  - task: AzureStaticWebApp@0
    inputs:
      app_location: '/Website'
      azure_static_web_apps_api_token: '2a4e71807dc78b337fb2d1eb224a7766aaa0113f697209dd32896ae02b659cbe0-17fc6189-21d5-4f17-b733-59db9daf34cb00352474'